---
language: php
php:
  - 5.4
  - 5.5
  - 5.6
before_script:
   - composer self-update
install:
  - composer install
script:
  - ./vendor/phpspec/phpspec/bin/phpspec run test/spec --format=pretty --no-code-generation -v
